# Generated by Django 4.1.7 on 2023-09-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('institute', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
    ]
