# Generated by Django 4.2.5 on 2023-09-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_studentdetail_id_studentdetail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='Id',
            new_name='id',
        ),
    ]
